services:
  admin.categorie:
        class: AppBundle\Admin\CategorieAdmin
        arguments: [~, AppBundle\Entity\Categorie, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Categories, group: "categorie" }
        public: true

  admin.plat:
        class: AppBundle\Admin\PlatAdmin
        arguments: [~, AppBundle\Entity\Plat, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Plats, group: "categorie" }
        public: true

  admin.choix:
        class: AppBundle\Admin\ChoixAdmin
        arguments: [~, AppBundle\Entity\Choix, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Choix, group: "categorie" }
        public: true

  admin.menus:
        class: AppBundle\Admin\MenuAdmin
        arguments: [~, AppBundle\Entity\Menu, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Menus, group: "categorie" }
        public: true