sonata_admin:
    persist_filters: true
    title:  'LPL Admin'
    dashboard:
        groups:
            categorie:
                label:           Plats & Menus
                label_catalogue: messages
                icon:            '<i class="fas fa-utensils"></i>'
sonata_block:
    default_contexts: [cms]
    blocks:
        # enable the SonataAdminBundle block
        sonata.admin.block.admin_list:
            contexts: [admin]